#+TITLE: Aelobdog's Personal Website
#+AUTHOR: Aelobdog
#+DESCRIPTION: credit for the css goes to Brian Kamotho. Taken from his website https://unwindprotect.com/
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./stylesheet.css"/>
#+OPTIONS: num:nil html-style:nil toc:nil author:

* Welcome
Hi ! Welcome to my personal website.
This page is mostly for my projects.
For my personal blog, visit [[https://aelobdog.github.io/aelobdog-writes][this page]].

* Projects
Here's a list of some of the projects
that I've made.

** 🢖 [[https://github.com/aelobdog/lih2][Lih2]]
Lih2 is a super simple blog maintenance
tool that I use for my personal blog.
It used sitefl as the markup language
for blog posts.
** 🢖 [[https://github.com/aelobdog/cuppu86][Cuppu86]]
Cuppu86 is an emulator backend for the
Intel 8086. It is a bunch of code that
is capable of executing about 98% of all
the instructions in the 8086 ISA. Clients
can be designed to use this project as a
backend for their emulators. All interrupt
related instructions (there are four) have
been left unimplemented.
** 🢖 [[https://github.com/aelobdog/bru][Bru]]
Bru is an HDL based electronics simulator
that works at the gate level. It works by
converting the HDL and simulation scripts
into a single Go(lang) file which, when
executed displays the results of the
simulation.
** 🢖 [[https://github.com/aelobdog/colon-lang][Colon]]
Colon is a dynamic, interpretted programming
language with a handmade lexer and parser
written in Go(lang). The syntax for the
language was inspired by an older project of
mine : [[https://github.com/aelobdog/axolotl][axolotl]]. The rest of the language was
designed with [[https://thorstenball.com/][Thorsten Ball]]'s excellent book
[[https://interpreterbook.com/][Write an interpretter in Go]].
** 🢖 [[https://github.com/aelobdog/sitefl][SiTeFL]]
SiTeFL, the Simple Text Formatting Language,
is exactly what it stands for. It is a markdown
like, minimal text formatting language which I
write all my blog posts in. It comes with a
template html and a sample stylesheet which are
fully customizable.

There is a web version of this program [[https://aelobdog.github.com/siteflon][here]].
** 🢖 [[https://github.com/aelobdog/dynar][DynAr]]
Dynar is a "preprocessor" for programs written
in the C programming language. It allows the
programmer to use dynamic, resizable arrays as
if they were a built-in feature in the language
itself. It also provides functionality to =push=,
=pop=, =insert= and =delete= elements from the
resizable arrays created.
